# HW2-task1

In [1]:
#라이브러리 import
import numpy as np

#activation functions
def sigmoid(x):
    return 1/(1+ np.exp(-x))

def de_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

def add_bias(x):
    x = np.c_[x,[0,0,0,0]]
    bias = 1
    for i in x:
        i[2] = i[1]
        i[1] = i[0]
        i[0] = bias 
    return x

#input layer
Input = np.array([[0,0], [0,1], [1,0], [1,1]])
#output layer
y = np.array([[0], [1], [1], [0]])

x = add_bias(Input)

#hidden weight
hidden_w = np.random.rand(3,2)
#output weight
output_w = np.random.rand(3,1)
#learning rate
alpha = 0.1

print("Random hidden weight: \n", hidden_w)
print("\nRandom output weight: \n", output_w)

#training
for i in range(100000):
    hidden_z = np.dot(x, hidden_w)
    hidden_a = sigmoid(hidden_z)

    output_i = add_bias(hidden_a)
    output_z = np.dot(output_i, output_w)
    output_a = sigmoid(output_z)

    #backpropagation
    output_delta = (y - output_a) * de_sigmoid(output_z)
    hidden_delta = output_delta.dot(output_w[1:].T) * de_sigmoid(hidden_z)
    
    #update weight
    output_w += alpha * output_i.T.dot(output_delta)
    hidden_w += alpha * x.T.dot(hidden_delta)
    
print("\n\nFinal hidden_weight: \n", hidden_w)    
print("\nFinal output_weight: \n", output_w)

print("\n\nOutput: ", output_a.T)

Random hidden weight: 
 [[0.78681352 0.56893329]
 [0.97453317 0.43059466]
 [0.85642749 0.54670908]]

Random output weight: 
 [[0.17401608]
 [0.10713061]
 [0.42702498]]


Final hidden_weight: 
 [[-3.01999313 -7.41278143]
 [ 6.72188874  4.83243667]
 [ 6.72522182  4.83324752]]

Final output_weight: 
 [[ -4.80227326]
 [ 10.313839  ]
 [-11.01727277]]


Output:  [[0.01300923 0.9888778  0.98887536 0.01144976]]
